apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcfmapi-deployment
  annotations: 
    kubernetes.io/change-cause: "Initial deployment of the app"

spec: 
  replicas: 3
  selector:
    matchLabels:
      app: bcfmapi
  template:
    metadata:
      labels:
        env: prod
        app: bcfmapi
        app.kubernetes.io/name: bcfmapi
    spec:
      containers: 
        - name: bcfmapi
          image: cagrieroglu/bcfmapi:v1
          ports:  
            - containerPort: 80
              name: http-bcfmapi
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"

---
apiVersion: v1
kind: Service
metadata: 
  name: bcfm-load-balancer
spec:
  selector:
    app: bcfmapi
  ports: 
    - name: bcfmapi-port
      protocol: TCP
      port: 9090
      targetPort: 80
  type: LoadBalancer